#!/usr/bin/env bash

# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

export choice=individual
export FILES=(
  # bigquery.gcp.upbound.io
  "bigquery.gcp.upbound.io_analyticshubdataexchangeiammembers.yaml"
  "bigquery.gcp.upbound.io_analyticshubdataexchanges.yaml"
  "bigquery.gcp.upbound.io_analyticshublistings.yaml"
  "bigquery.gcp.upbound.io_analyticshublistingsubscriptions.yaml"
  "bigquery.gcp.upbound.io_connections.yaml"
  "bigquery.gcp.upbound.io_datasetaccesses.yaml"
  "bigquery.gcp.upbound.io_datasetiambindings.yaml"
  "bigquery.gcp.upbound.io_datasetiammembers.yaml"
  "bigquery.gcp.upbound.io_datasetiampolicies.yaml"
  "bigquery.gcp.upbound.io_datasets.yaml"
  "bigquery.gcp.upbound.io_datatransferconfigs.yaml"
  "bigquery.gcp.upbound.io_jobs.yaml"
  "bigquery.gcp.upbound.io_reservationassignments.yaml"
  "bigquery.gcp.upbound.io_reservations.yaml"
  "bigquery.gcp.upbound.io_routines.yaml"
  "bigquery.gcp.upbound.io_tableiambindings.yaml"
  "bigquery.gcp.upbound.io_tableiammembers.yaml"
  "bigquery.gcp.upbound.io_tableiampolicies.yaml"
  "bigquery.gcp.upbound.io_tables.yaml"
  # bigtable.gcp.upbound.io
  "bigtable.gcp.upbound.io_appprofiles.yaml"
  "bigtable.gcp.upbound.io_garbagecollectionpolicies.yaml"
  "bigtable.gcp.upbound.io_instanceiambindings.yaml"
  "bigtable.gcp.upbound.io_instanceiammembers.yaml"
  "bigtable.gcp.upbound.io_instanceiampolicies.yaml"
  "bigtable.gcp.upbound.io_instances.yaml"
  "bigtable.gcp.upbound.io_tableiambindings.yaml"
  "bigtable.gcp.upbound.io_tableiammembers.yaml"
  "bigtable.gcp.upbound.io_tableiampolicies.yaml"
  "bigtable.gcp.upbound.io_tables.yaml"
  # cloudrun.gcp.upbound.io
  "cloudrun.gcp.upbound.io_domainmappings.yaml"
  "cloudrun.gcp.upbound.io_serviceiammembers.yaml"
  "cloudrun.gcp.upbound.io_services.yaml"
  "cloudrun.gcp.upbound.io_v2jobs.yaml"
  "cloudrun.gcp.upbound.io_v2services.yaml"
  # compute.gcp.upbound.io
  "compute.gcp.upbound.io_addresses.yaml"
  "compute.gcp.upbound.io_attacheddisks.yaml"
  "compute.gcp.upbound.io_autoscalers.yaml"
  "compute.gcp.upbound.io_backendbuckets.yaml"
  "compute.gcp.upbound.io_backendbucketsignedurlkeys.yaml"
  "compute.gcp.upbound.io_backendservices.yaml"
  "compute.gcp.upbound.io_backendservicesignedurlkeys.yaml"
  "compute.gcp.upbound.io_diskiammembers.yaml"
  "compute.gcp.upbound.io_diskresourcepolicyattachments.yaml"
  "compute.gcp.upbound.io_disks.yaml"
  "compute.gcp.upbound.io_externalvpngateways.yaml"
  "compute.gcp.upbound.io_firewallpolicies.yaml"
  "compute.gcp.upbound.io_firewallpolicyassociations.yaml"
  "compute.gcp.upbound.io_firewallpolicyrules.yaml"
  "compute.gcp.upbound.io_firewalls.yaml"
  "compute.gcp.upbound.io_forwardingrules.yaml"
  "compute.gcp.upbound.io_globaladdresses.yaml"
  "compute.gcp.upbound.io_globalforwardingrules.yaml"
  "compute.gcp.upbound.io_globalnetworkendpointgroups.yaml"
  "compute.gcp.upbound.io_globalnetworkendpoints.yaml"
  "compute.gcp.upbound.io_havpngateways.yaml"
  "compute.gcp.upbound.io_healthchecks.yaml"
  "compute.gcp.upbound.io_httphealthchecks.yaml"
  "compute.gcp.upbound.io_httpshealthchecks.yaml"
  "compute.gcp.upbound.io_imageiammembers.yaml"
  "compute.gcp.upbound.io_images.yaml"
  "compute.gcp.upbound.io_instancefromtemplates.yaml"
  "compute.gcp.upbound.io_instancegroupmanagers.yaml"
  "compute.gcp.upbound.io_instancegroupnamedports.yaml"
  "compute.gcp.upbound.io_instancegroups.yaml"
  "compute.gcp.upbound.io_instanceiammembers.yaml"
  "compute.gcp.upbound.io_instances.yaml"
  "compute.gcp.upbound.io_instancetemplates.yaml"
  "compute.gcp.upbound.io_interconnectattachments.yaml"
  "compute.gcp.upbound.io_managedsslcertificates.yaml"
  "compute.gcp.upbound.io_networkendpointgroups.yaml"
  "compute.gcp.upbound.io_networkendpoints.yaml"
  "compute.gcp.upbound.io_networkfirewallpolicies.yaml"
  "compute.gcp.upbound.io_networkfirewallpolicyassociations.yaml"
  "compute.gcp.upbound.io_networkfirewallpolicyrules.yaml"
  "compute.gcp.upbound.io_networkpeeringroutesconfigs.yaml"
  "compute.gcp.upbound.io_networkpeerings.yaml"
  "compute.gcp.upbound.io_networks.yaml"
  "compute.gcp.upbound.io_nodegroups.yaml"
  "compute.gcp.upbound.io_nodetemplates.yaml"
  "compute.gcp.upbound.io_packetmirrorings.yaml"
  "compute.gcp.upbound.io_perinstanceconfigs.yaml"
  "compute.gcp.upbound.io_projectdefaultnetworktiers.yaml"
  "compute.gcp.upbound.io_projectmetadata.yaml"
  "compute.gcp.upbound.io_projectmetadataitems.yaml"
  "compute.gcp.upbound.io_regionautoscalers.yaml"
  "compute.gcp.upbound.io_regionbackendservices.yaml"
  "compute.gcp.upbound.io_regiondiskiammembers.yaml"
  "compute.gcp.upbound.io_regiondiskresourcepolicyattachments.yaml"
  "compute.gcp.upbound.io_regiondisks.yaml"
  "compute.gcp.upbound.io_regionhealthchecks.yaml"
  "compute.gcp.upbound.io_regioninstancegroupmanagers.yaml"
  "compute.gcp.upbound.io_regionnetworkendpointgroups.yaml"
  "compute.gcp.upbound.io_regionnetworkendpoints.yaml"
  "compute.gcp.upbound.io_regionnetworkfirewallpolicies.yaml"
  "compute.gcp.upbound.io_regionnetworkfirewallpolicyassociations.yaml"
  "compute.gcp.upbound.io_regionperinstanceconfigs.yaml"
  "compute.gcp.upbound.io_regionsecuritypolicies.yaml"
  "compute.gcp.upbound.io_regionsslcertificates.yaml"
  "compute.gcp.upbound.io_regionsslpolicies.yaml"
  "compute.gcp.upbound.io_regiontargethttpproxies.yaml"
  "compute.gcp.upbound.io_regiontargethttpsproxies.yaml"
  "compute.gcp.upbound.io_regiontargettcpproxies.yaml"
  "compute.gcp.upbound.io_regionurlmaps.yaml"
  "compute.gcp.upbound.io_reservations.yaml"
  "compute.gcp.upbound.io_resourcepolicies.yaml"
  "compute.gcp.upbound.io_routerinterfaces.yaml"
  "compute.gcp.upbound.io_routernats.yaml"
  "compute.gcp.upbound.io_routerpeers.yaml"
  "compute.gcp.upbound.io_routers.yaml"
  "compute.gcp.upbound.io_routes.yaml"
  "compute.gcp.upbound.io_securitypolicies.yaml"
  "compute.gcp.upbound.io_serviceattachments.yaml"
  "compute.gcp.upbound.io_sharedvpchostprojects.yaml"
  "compute.gcp.upbound.io_sharedvpcserviceprojects.yaml"
  "compute.gcp.upbound.io_snapshotiammembers.yaml"
  "compute.gcp.upbound.io_snapshots.yaml"
  "compute.gcp.upbound.io_sslcertificates.yaml"
  "compute.gcp.upbound.io_sslpolicies.yaml"
  "compute.gcp.upbound.io_subnetworkiammembers.yaml"
  "compute.gcp.upbound.io_subnetworks.yaml"
  "compute.gcp.upbound.io_targetgrpcproxies.yaml"
  "compute.gcp.upbound.io_targethttpproxies.yaml"
  "compute.gcp.upbound.io_targethttpsproxies.yaml"
  "compute.gcp.upbound.io_targetinstances.yaml"
  "compute.gcp.upbound.io_targetpools.yaml"
  "compute.gcp.upbound.io_targetsslproxies.yaml"
  "compute.gcp.upbound.io_targettcpproxies.yaml"
  "compute.gcp.upbound.io_urlmaps.yaml"
  "compute.gcp.upbound.io_vpngateways.yaml"
  "compute.gcp.upbound.io_vpntunnels.yaml"
  # container.gcp.upbound.io
  "container.gcp.upbound.io_clusters.yaml"
  "container.gcp.upbound.io_nodepools.yaml"
  "container.gcp.upbound.io_registries.yaml"
  # dns.gcp.upbound.io
  "dns.gcp.upbound.io_managedzoneiammembers.yaml"
  "dns.gcp.upbound.io_managedzones.yaml"
  "dns.gcp.upbound.io_policies.yaml"
  "dns.gcp.upbound.io_recordsets.yaml"
  "dns.gcp.upbound.io_responsepolicies.yaml"
  "dns.gcp.upbound.io_responsepolicyrules.yaml"
  # gke.gcp.upbound.io
  "gke.gcp.upbound.io_backupbackupplans.yaml"
  # iam.gcp.upbound.io
  "iam.gcp.upbound.io_workloadidentitypoolproviders.yaml"
  "iam.gcp.upbound.io_workloadidentitypools.yaml"
  # kms.gcp.upbound.io
  "kms.gcp.upbound.io_cryptokeyiammembers.yaml"
  "kms.gcp.upbound.io_cryptokeys.yaml"
  "kms.gcp.upbound.io_cryptokeyversions.yaml"
  "kms.gcp.upbound.io_keyringiammembers.yaml"
  "kms.gcp.upbound.io_keyringimportjobs.yaml"
  "kms.gcp.upbound.io_keyrings.yaml"
  "kms.gcp.upbound.io_secretciphertexts.yaml"
  # logging.gcp.upbound.io
  "logging.gcp.upbound.io_folderbucketconfigs.yaml"
  "logging.gcp.upbound.io_folderexclusions.yaml"
  "logging.gcp.upbound.io_foldersinks.yaml"
  "logging.gcp.upbound.io_logviews.yaml"
  "logging.gcp.upbound.io_metrics.yaml"
  "logging.gcp.upbound.io_projectbucketconfigs.yaml"
  "logging.gcp.upbound.io_projectexclusions.yaml"
  "logging.gcp.upbound.io_projectsinks.yaml"
  # monitoring.gcp.upbound.io
  "monitoring.gcp.upbound.io_alertpolicies.yaml"
  "monitoring.gcp.upbound.io_customservices.yaml"
  "monitoring.gcp.upbound.io_dashboards.yaml"
  "monitoring.gcp.upbound.io_groups.yaml"
  "monitoring.gcp.upbound.io_metricdescriptors.yaml"
  "monitoring.gcp.upbound.io_notificationchannels.yaml"
  "monitoring.gcp.upbound.io_services.yaml"
  "monitoring.gcp.upbound.io_sloes.yaml"
  "monitoring.gcp.upbound.io_uptimecheckconfigs.yaml"
  # pubsub.gcp.upbound.io
  "pubsub.gcp.upbound.io_litereservations.yaml"
  "pubsub.gcp.upbound.io_litesubscriptions.yaml"
  "pubsub.gcp.upbound.io_litetopics.yaml"
  "pubsub.gcp.upbound.io_schemas.yaml"
  "pubsub.gcp.upbound.io_subscriptioniammembers.yaml"
  "pubsub.gcp.upbound.io_subscriptions.yaml"
  "pubsub.gcp.upbound.io_topiciammembers.yaml"
  "pubsub.gcp.upbound.io_topics.yaml"
  # redis.gcp.upbound.io
  "redis.gcp.upbound.io_clusters.yaml"
  "redis.gcp.upbound.io_clusterusercreatedconnections.yaml"
  "redis.gcp.upbound.io_instances.yaml"
  # secretmanager.gcp.upbound.io
  "secretmanager.gcp.upbound.io_secretiammembers.yaml"
  "secretmanager.gcp.upbound.io_secrets.yaml"
  "secretmanager.gcp.upbound.io_secretversions.yaml"
  # spanner.gcp.upbound.io
  "spanner.gcp.upbound.io_databaseiammembers.yaml"
  "spanner.gcp.upbound.io_databases.yaml"
  "spanner.gcp.upbound.io_instanceiammembers.yaml"
  "spanner.gcp.upbound.io_instances.yaml"
  # sql.gcp.upbound.io
  "sql.gcp.upbound.io_databaseinstances.yaml"
  "sql.gcp.upbound.io_databases.yaml"
  "sql.gcp.upbound.io_sourcerepresentationinstances.yaml"
  "sql.gcp.upbound.io_sslcerts.yaml"
  "sql.gcp.upbound.io_users.yaml"
  # storage.gcp.upbound.io
  "storage.gcp.upbound.io_bucketaccesscontrols.yaml"
  "storage.gcp.upbound.io_bucketacls.yaml"
  "storage.gcp.upbound.io_bucketiammembers.yaml"
  "storage.gcp.upbound.io_bucketiampolicies.yaml"
  "storage.gcp.upbound.io_bucketobjects.yaml"
  "storage.gcp.upbound.io_buckets.yaml"
  "storage.gcp.upbound.io_defaultobjectaccesscontrols.yaml"
  "storage.gcp.upbound.io_defaultobjectacls.yaml"
  "storage.gcp.upbound.io_hmackeys.yaml"
  "storage.gcp.upbound.io_managedfolderiammembers.yaml"
  "storage.gcp.upbound.io_managedfolders.yaml"
  "storage.gcp.upbound.io_notifications.yaml"
  "storage.gcp.upbound.io_objectaccesscontrols.yaml"
  "storage.gcp.upbound.io_objectacls.yaml"
  # vertexai.gcp.upbound.io
  "vertexai.gcp.upbound.io_datasets.yaml"
  "vertexai.gcp.upbound.io_featurestoreentitytypes.yaml"
  "vertexai.gcp.upbound.io_featurestores.yaml"
  "vertexai.gcp.upbound.io_tensorboards.yaml"
)

# renovate: datasource=github-tags depName=upbound/provider-gcp
export VERSION=v2.5.0

function generate_url {
  local crd_file=$1
  echo "https://raw.githubusercontent.com/upbound/provider-gcp/${VERSION}/package/crds/${crd_file}"
}
